version: "3.8"

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: super_user
      POSTGRES_DB: crypto_data
    expose:
      - 5432
    ports:
      - 5432:5432

    volumes:
      - crypto_data:/var/lib/postgresql/data
  
  server:
    build: .
    depends_on: 
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432

      ip_address: 0.0.0.0
      port: 3000
    expose:
      - 3000
    ports:
      - 3000:3000

volumes:
  crypto_data: