version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: super_user
      POSTGRES_DB: crypto_data
    expose:
      - 5432
    ports:
      - 5432:5432

    volumes:
      - crypto_data:/var/lib/postgresql/data

volumes:
  crypto_data:
