version: "3.8"

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: super_user
      POSTGRES_DB: crypto_data
    expose:
      - 5432
    ports:
      - 5432:5432

    volumes:
      - crypto_data:/var/lib/postgresql/data
      
volumes:
  crypto_data:
  
  # server:
  #   image: crypto_analyzer_server
  #   depends_on: 
  #     - database
  #   environment:
  #     DB_HOST: 0.0.0.0
  #     DB_PORT: 5432

  #     ip_address: 0.0.0.0
  #     port: 3000
  #     # - DATABASE_URL=postgres://super_user:password@0.0.0.0:5432/crypto_data
  #   expose:
  #     - 3000
  #   ports:
  #     - 3000:3000
