[package]
name = "universal_transaction"
version = "0.1.0"
authors=["1x2kb 1x2kb@github.com"]

[dependencies]
rust_decimal.workspace = true
kraken_ledgers = { path = "../kraken_ledgers" }
coinbase_parser = { path = "../coinbase_parser" }