[package]
name = "coinbase_transactions"
version = "0.1.0"
authors = ["1x2kb 1x2kb@github.com"]

[dependencies]
csv.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust_decimal.workspace = true

[dev-dependencies]
rand = "*"
