[package]
name = "crypto_database"
version.workspace = true
edition = "2021"

[dependencies]
diesel = { version = "2.0.3", features = ["postgres", "chrono", "numeric"] }
chrono.workspace = true
rust_decimal.workspace = true
models = { path = "../models" }

[dev-dependencies]
dotenvy = "0.15.7"
